export const AUTH_TEXT = {
  login: {
    title: "Welcome Back",
    subtitle: "Login to your account",
    emailLabel: "Enter Email Address or Phone Number",
    passwordLabel: "Password",
    submitButton: "Login",
    createAccount: "Create a new account",
    forgotPassword: "Forgot password?",
    or: "or",
    Google: "Continue with Google",
    Guest: "Continue as Guest",
  },

  register: {
    title: "Welcome to AnimeKey",
    emailLabel: "Enter Email",
    phoneLabel: "Enter Phone",
    firstLabel: "First Name",
    lastLabel: "Last Name",
    passwordLabel: "Password",
    cnfpasswordLabel: "Confirm Password",
    monthLabel: "MM",
    dayLabel: "DD",
    yearLabel: "YYYY",
    submitButton: "Create Account",
    terms: "I've read and accept",
    hasAccount: "Already have an account?",
  },
};
